:app_name: "test_app"
:user_id: "1619-6456-1164"
:access_key: ""
:secret_access_key: ""
:ami: "ami-4f7a9f26"
:size: small
:polling_time: "30.seconds"
:minimum_instances: 2
:maximum_instances: 3
:ec2_dir: "/Users/auser/.ec2"
:keypair: auser
:os: ubuntu
:host_port: 80
:client_port: 8001
:shared_bucket: "poolparty-app-data"
:services: nginx
:environment: production
:contract_when: |
  web > 10
  cpu < 0.2
:expand_when: |
  cpu > 0.85
  web < 5